name: Teste CI - Cypress 

on:
  push:
    branches: [ "main" ]
  #workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    - name: Instalar Dependencias
      run: npm install 
    
    - name: Executar testes
      run: npm test

    - name: Gerar relatório Allure
      run: npm run report:generate

    - name: Publicar relatório no Gh Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
